/**
 * User Service contract
 * This is a sample specification for user service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CodegenSkillsApi) {
      root.CodegenSkillsApi = {};
    }
    root.CodegenSkillsApi.Skill = factory(root.CodegenSkillsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Skill model module.
   * @module model/Skill
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Skill</code>.
   * @alias module:model/Skill
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;


    _this['name'] = name;


  };

  /**
   * Constructs a <code>Skill</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Skill} obj Optional instance to populate.
   * @return {module:model/Skill} The populated <code>Skill</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('study')) {
        obj['study'] = ApiClient.convertToType(data['study'], 'Number');
      }
      if (data.hasOwnProperty('progress')) {
        obj['progress'] = ApiClient.convertToType(data['progress'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} study
   */
  exports.prototype['study'] = undefined;
  /**
   * @member {Number} progress
   */
  exports.prototype['progress'] = undefined;



  return exports;
}));


