/**
 * User Service contract
 * This is a sample specification for user service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodegenSkillsApi);
  }
}(this, function(expect, CodegenSkillsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CodegenSkillsApi.SkillApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SkillApi', function() {
    describe('createSkill', function() {
      it('should call createSkill successfully', function(done) {
        //uncomment below and update the code to test createSkill
        //instance.createSkill(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSkill', function() {
      it('should call deleteSkill successfully', function(done) {
        //uncomment below and update the code to test deleteSkill
        //instance.deleteSkill(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSkillById', function() {
      it('should call getSkillById successfully', function(done) {
        //uncomment below and update the code to test getSkillById
        //instance.getSkillById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSkills', function() {
      it('should call getSkills successfully', function(done) {
        //uncomment below and update the code to test getSkills
        //instance.getSkills(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSkill', function() {
      it('should call updateSkill successfully', function(done) {
        //uncomment below and update the code to test updateSkill
        //instance.updateSkill(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
