CREATE TABLE IF NOT EXISTS SKILL_DB (ID IDENTITY NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, STUDY DOUBLE, PROGRESS DOUBLE);

INSERT INTO SKILL_DB  VALUES (default, 'Java', 1030.0, 0.0);
INSERT INTO SKILL_DB  VALUES (default, 'Kotlin', 900.0, 0.0);
INSERT INTO SKILL_DB  VALUES (default, 'Jenkins', 150.0, 0.0);
INSERT INTO SKILL_DB  VALUES (default, 'Docker', 240.0, 0.0);