CREATE TABLE IF NOT EXISTS SKILL_DB (ID IDENTITY NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

INSERT INTO SKILL_DB  VALUES (default, 'Java');
INSERT INTO SKILL_DB  VALUES (default, 'Kotlin');
INSERT INTO SKILL_DB  VALUES (default, 'Jenkins');
INSERT INTO SKILL_DB  VALUES (default, 'Docker');